services:
  # MongoDB Database
  mongodb:
    image: mongo:latest
    env_file: .env
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  mongo_data: